services:
  gateway:
    build:
      context: ./../src/gateway
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8002
      - VAULT_SERVICE_URL=http://vault-service:8003
    depends_on:
      - auth-service
    networks:
      - backend

  auth-service:
    build:
      context: ./../src/auth_service
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=auth_user_docker
      - MYSQL_PASSWORD=auth_user_password
      - MYSQL_DB=auth
      - JWT_SECRET=1234 
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth
      MYSQL_USER: auth_user_docker
      MYSQL_PASSWORD: auth_user_password
    volumes:
      - ./../src/auth_service/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge

