#!/bin/bash

# Define the virtual environment activation paths
VENV="venv/bin/activate"

auth_venv="$(pwd)/auth_service/$VENV"
vault_venv="$(pwd)/vault_service/$VENV"
gateway_venv="$(pwd)/gateway_service/$VENV"

# Run auth service
cd auth_service
source "$auth_venv"
fastapi dev --port 8002 --app server --host 0.0.0.0 auth_service.py &
deactivate
cd ..

# Run vault service
cd vault_service
$(echo pwd)
source "$vault_venv"
fastapi dev --port 8003 --app server --host 0.0.0.0 vault_service.py &
deactivate
cd ..

# Run gateway service
cd gateway_service
source "$gateway_venv"
fastapi dev --port 8001 --app server --host 0.0.0.0 gateway_service.py &
deactivate
cd ..
